name: Create New Release

on:
  push:
    paths:
      - '**'
      # - '**/*(.md)+'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Prepare Files For Release"
        run: echo ${{ inputs.release-version }}
