name: Testing a Manual dispatch

on:
  workflow_dispatch:
    inputs:
      release:
        description: some random text for testing
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Prepare Files For Release"
        run: echo ${{ inputs.release }}