name: Testing a Manual dispatch

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "echo an input"
        run: echo ''