# test that a "registered" workflow can then be altered to a manual dispatch
name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout

    - name: test action
      run: echo 'test'

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1

    - name: make test file
      run: touch test
